/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author ndoutou
 */
public class Pave_numerik extends javax.swing.JPanel {

    /**
     * Creates new form Pave_numerik
     */
    public Pave_numerik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zerojButton = new javax.swing.JButton();
        unjButton = new javax.swing.JButton();
        deuxjButton = new javax.swing.JButton();
        troisjButton = new javax.swing.JButton();
        quatrejButton = new javax.swing.JButton();
        cinqjButton = new javax.swing.JButton();
        sixjButton = new javax.swing.JButton();
        septjButton = new javax.swing.JButton();
        huitjButton = new javax.swing.JButton();
        neufjButton = new javax.swing.JButton();
        virgulejButton = new javax.swing.JButton();
        plus_ou_plusjButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 3, 2, 2));

        zerojButton.setText("0");
        add(zerojButton);

        unjButton.setText("1");
        add(unjButton);

        deuxjButton.setText("2");
        add(deuxjButton);

        troisjButton.setText("3");
        add(troisjButton);

        quatrejButton.setText("4");
        add(quatrejButton);

        cinqjButton.setText("5");
        add(cinqjButton);

        sixjButton.setText("6");
        add(sixjButton);

        septjButton.setText("7");
        add(septjButton);

        huitjButton.setText("8");
        add(huitjButton);

        neufjButton.setText("9");
        add(neufjButton);

        virgulejButton.setText(".");
        add(virgulejButton);

        plus_ou_plusjButton.setText("+/-");
        add(plus_ou_plusjButton);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cinqjButton;
    private javax.swing.JButton deuxjButton;
    private javax.swing.JButton huitjButton;
    private javax.swing.JButton neufjButton;
    private javax.swing.JButton plus_ou_plusjButton;
    private javax.swing.JButton quatrejButton;
    private javax.swing.JButton septjButton;
    private javax.swing.JButton sixjButton;
    private javax.swing.JButton troisjButton;
    private javax.swing.JButton unjButton;
    private javax.swing.JButton virgulejButton;
    private javax.swing.JButton zerojButton;
    // End of variables declaration//GEN-END:variables
}
