/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.calc.calculatrice;

/**
 *
 * @author ndoutou
 */
public class Pave_resultat extends javax.swing.JPanel {

    /**
     * Creates new form Pave_resultat
     */
    public Pave_resultat() {
        initComponents();
    }

    /**
     * on délègue l'affichage du texte au label. Pas besoin d'Observer.
     *
     * @param texte
     */
    public void afficher(String texte) {
        resultatjLabel.setText(texte);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultatjLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));

        resultatjLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultatjLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultatjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultatjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel resultatjLabel;
    // End of variables declaration//GEN-END:variables
}
